[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "miles-tails"
authors = [{name = "NCAR MILES Group", email = "miles@ucar.edu"}]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "miles-credit",
    "scipy",
]

[tool.setuptools]
packages = ["tails"]

[tool.setuptools_scm]
version_file = "tails/_version.py"

[tool.ruff]
target-version = "py311"
src = ["tails", "tests"]
line-length = 180

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = ["E402"]

[tool.ruff.lint.pydocstyle]
convention = "google"