flux_length_days: 15
forecast_start_times:
- '2022-09-02 00:00:00'
- '2022-09-09 12:00:00'
- '2022-09-22 00:00:00'
ic_index: 0
interfaces:
- 1000.0
- 987.2
- 984.7
- 981.2
n_flux_total: 2000
n_shoot_per_interface: 2000
n_workers: 4
output_dir: ./results_mar18
shoot_length_days: 30
single_ic_mode: true
state_A: 1008
state_B: 975
use_cps: true
