# --------------------------------------------------------------------------------------------------------------------- #
# This yaml file implements 6 hourly state-in-state-out wxformer model
# on NSF NCAR HPCs (casper.ucar.edu and derecho.hpc.ucar.edu) 
# The model is trained on 1 hourly model-level ERA5 data with top solar irradiance, geopotential, and land-sea mask
# Output variables: model level [U, V, T, Q], single level [SP, t2m], and 500 hPa [U, V, T, Z, Q]
# --------------------------------------------------------------------------------------------------------------------- #
save_loc: '/glade/campaign/cisl/aiml/credit/models/one_degree_wxformer_6hr_ensemble/' # '/glade/derecho/scratch/schreck/CREDIT_runs/ensemble/scheduler/'
seed: 2000

data:
    # upper-air variables
    variables: ['U','V','T','Q']
    level_ids: [10, 30, 40, 50, 60, 70, 80, 90, 95, 100, 105, 110, 120, 130, 136, 137]
    save_loc: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/all_in_one/ERA5_mlevel_cesm_6h_lev16_*.zarr'
    
    # surface variables
    surface_variables: ['SP','t2m','V500','U500','T500','Z500','Q500']
    save_loc_surface: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/all_in_one/ERA5_mlevel_cesm_6h_lev16_*.zarr'
    
    # dynamic forcing variables
    dynamic_forcing_variables: ['tsi']
    save_loc_dynamic_forcing: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/all_in_one/ERA5_mlevel_cesm_6h_lev16_*.zarr'
    
    # static variables
    static_variables: ['Z_GDS4_SFC','LSM'] 
    save_loc_static: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/static/ERA5_mlevel_cesm_static.zarr'
    # save_loc_static: '/glade/campaign/cisl/aiml/credit/static_scalers/static_norm_20250416.nc'
    
    # mean / std path
    mean_path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/mean_std/mean_6h_1979_2018_cesm.nc'
    # regular z-score version
    # std_path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/mean_std/std_6h_1979_2018_cesm.nc'
    # residual norm version
    std_path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/mean_std/std_residual_6h_1979_2018_cesm.nc'
    
    # train / validation split
    train_years: [1979, 2018]
    valid_years: [2018, 2019]
    
    # data workflow
    scaler_type: 'std_new'
    
    # state-in-state-out
    history_len: 1
    valid_history_len: 1
    
    forecast_len: 0
    valid_forecast_len: 0
    
    one_shot: True
    
    # 1 for hourly model
    lead_time_periods: 6
    
    # do not use skip_period
    skip_periods: null
    
    # compatible with the old 'std'
    static_first: True

    dataset_type: ERA5_MultiStep_Batcher # ERA5_and_Forcing_MultiStep MultiprocessingBatcherPrefetch ERA5_MultiStep_Batcher MultiprocessingBatcher
    
trainer:
    type: era5 # <---------- change to your type: single/multi-step training

    mode: ddp
    cpu_offload: False
    activation_checkpoint: True
    
    load_weights: True
    load_optimizer: True
    load_scaler: True
    load_scheduler: True

    skip_validation: False
    update_learning_rate: False

    save_backup_weights: False
    save_best_weights: False
    
    learning_rate: 1.0e-05
    weight_decay: 1.0e-06
    save_metric_vars: ["std", "rmse"]
    
    train_batch_size: 1
    valid_batch_size: 1
    ensemble_size: 10
    
    batches_per_epoch: 1000 # Total number of samples = 341,880  (1h) ~56,960 (6h)
    valid_batches_per_epoch: 10
    stopping_patience: 999
    
    start_epoch: 0
    num_epoch: 3
    reload_epoch: True
    epochs: &epochs 20
     
    use_scheduler: True
    scheduler: {'scheduler_type': 'cosine-annealing', 'T_max': *epochs,  'last_epoch': -1}
    
    # Automatic Mixed Precision: False
    amp: False
    
    # rescale loss as loss = loss / grad_accum_every
    grad_accum_every: 1 
    # gradient clipping
    grad_max_norm: 'dynamic'
    
    # number of workers
    thread_workers: 4
    valid_thread_workers: 4

    # compile 
    # compile: True
    prefetch_factor: 4


model:
    # crossformer example
    type: "crossformer-style"
    frames: 1                         # number of input states (default: 1)
    image_height: 192                 # number of latitude grids (default: 640)
    image_width: 288                 # number of longitude grids (default: 1280)
    levels: 16                        # number of upper-air variable levels (default: 15)
    channels: 4                       # upper-air variable channels
    surface_channels: 7               # surface variable channels
    input_only_channels: 3            # dynamic forcing, forcing, static channels
    output_only_channels: 0           # diagnostic variable channels
    
    patch_width: 1                    # number of latitude grids in each 3D patch (default: 1)
    patch_height: 1                   # number of longitude grids in each 3D patch (default: 1)
    frame_patch_size: 1               # number of input states in each 3D patch (default: 1)
    
    dim: [256, 512, 1024, 2048]        # Dimensionality of each layer
    depth: [2, 2, 8, 2]               # Depth of each layer
    global_window_size: [8, 4, 2, 1] # Global window size for each layer
    local_window_size: 3             # Local window size
    cross_embed_kernel_sizes:         # kernel sizes for cross-embedding
    - [4, 8, 16, 32]
    - [2, 4]
    - [2, 4]
    - [2, 4]
    cross_embed_strides: [2, 2, 2, 2] # Strides for cross-embedding (default: [4, 2, 2, 2])
    attn_dropout: 0.                  # Dropout probability for attention layers (default: 0.0)
    ff_dropout: 0.                    # Dropout probability for feed-forward layers (default: 0.0)
    
    # use interpolation to match the output size
    interp: True

    # spectral norm
    use_spectral_norm: True

    # noise injection
    noise_latent_dim: 442
    # encoder_noise_factor: 0.04971295522390862
    decoder_noise_factor: 0.235
    encoder_noise: False
    freeze: False

    # decay_rate: 0.5
    # endpoint: 0.0
    
    # map boundary padding
    padding_conf:
        activate: True
        mode: earth
        pad_lat: 48
        pad_lon: 48
        
    post_conf: 
        activate: True
        tracer_fixer:
            activate: True
            denorm: True
            tracer_name: ['Q', 'Q500']
            tracer_thres: [1e-8, 1e-8]
    
loss: 
    # the main training loss
    training_loss: "KCRPS"
    
    # power loss (x), spectral_loss (x)
    use_power_loss: False
    use_spectral_loss: False
    
    # use latitude weighting
    use_latitude_weights: True
    latitude_weights: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_mlevel_cesm_stage1/static/ERA5_mlevel_cesm_static.zarr'
    
    # turn-off variable weighting
    use_variable_weights: False
    
predict:
    mode: none
    batch_size: 1
    ensemble_size: &ensemble_size 100
    # ensemble_method:
    #     type: "bred_vector"
    forecasts:
        type: "custom"       # keep it as "custom"
        start_year: 2022     # year of the first initialization (where rollout will start)
        start_month: 1       # month of the first initialization
        start_day: 1         # day of the first initialization
        start_hours: [0]     # hour-of-day for each initialization, 0 for 00Z, 12 for 12Z
        duration: 365          # number of days to initialize, starting from the (year, mon, day) above
                             # duration should be divisible by the number of GPUs 
                             # (e.g., duration: 384 for 365-day rollout using 32 GPUs)
        days: 15             # forecast lead time as days (1 means 24-hour forecast)
        
    metadata: '/glade/u/home/akn7/miles-credit/credit/metadata/era5.yaml'
    save_forecast: '/glade/derecho/scratch/schreck/CREDIT_runs/ensemble/scheduler/netcdf_pressure_interp'
    static_fields: '/glade/campaign/cisl/aiml/credit/static_scalers/static_whole_20250416_1deg.nc'
    # static_fields: "/glade/campaign/cisl/aiml/credit/static_scalers/static_variables_ERA5_zhght_onedeg.nc"
    
    # turn-off low-pass filter
    use_laplace_filter: False

    interp_pressure:
        interp_fields: ["U", "V", "T", "Q"]
        q_var: "Q"
        surface_pressure_var: "SP"
        # model_level_file: "/glade/derecho/scratch/kjmayer/CREDIT_runs/S2Socnlndatm_MLdata/b.e21.CREDIT_climate.statics_1.0deg_32levs_latlon_F32_hyai_fixed.nc"
        # a_model_name: "hyam"
        # b_model_name: "hybm"
        # a_half_name: "hyai"
        # b_half_name: "hybi"
        pressure_levels: [500.0, 700.0, 850.0]

    ensemble:
        noise:
            type: "spherical"  # "gaussian", "red", "white", "pink"       
            amplitude: 0.25 
            smoothness: 2.0
            length_scale: 3.0
            padding_conf:
                activate: True
                mode: earth
                pad_lat: [160, 160]
                pad_lon: [112, 112]

        bred_vector:
            enabled: true
            num_cycles: *ensemble_size
            hemispheric_rescale: true
            perturb_channel_idx: 69 # Z500. Set to None to do the full tensor
            integration_steps: 1 # 50
            bred_time_lag: 6 # 48
            amplitude: 0.25
            weights: [
                0.4014972 , 0.39774364, 0.3792097 , 0.38236109, 0.40767634,
                0.39912404, 0.34785054, 0.33406586, 0.33808283, 0.3481379 ,
                0.35312887, 0.35      , 0.32093613, 0.31208973, 0.31432467,
                0.31496031, 0.33391616, 0.35594943, 0.34669872, 0.35312887,
                0.38288379, 0.37536649, 0.31906112, 0.3057777 , 0.30951575,
                0.31984371, 0.32680269, 0.32649655, 0.30099834, 0.29983329,
                0.30331502, 0.30397368, 0.40112342, 0.38820098, 0.38431758,
                0.39051248, 0.40112342, 0.35496479, 0.33045423, 0.32893768,
                0.31543621, 0.31953091, 0.3254228 , 0.3324154 , 0.32109189,
                0.29664794, 0.26907248, 0.25845696, 0.23194827, 0.34102786,
                0.29647934, 0.32848135, 0.43703547, 0.4014972 , 0.40435133,
                0.41231056, 0.40298883, 0.39987498, 0.39987498, 0.39812058,
                0.38470768, 0.3748333 , 0.36959437, 0.36864617, 0.28231188,
                0.24677925, 0.31064449, 0.34029399, 0.31288976, 0.26645825,
                0.40112342
            ]

        temporal_noise:
            enabled: false
            temporal_correlation: 0.95
            perturbation_std: 0.15
            hemispheric_rescale: true

pbs: #derecho
    conda: "/glade/work/akn7/conda-envs/credit-derecho"
    project: "NAML0001"
    job_name: "style-wxf"
    walltime: "12:00:00"
    nodes: 8
    ncpus: 64
    ngpus: 4
    mem: '480GB'
    queue: 'main'
